version: '3.8'
services:
  mongo: 
    image: mongo:7.0.2
    ports:
      - 27017:27017
    networks:
      - my_networks
  
  express:
    image: mongo-express:1.0.0-20-alpine3.18
    environment:
      ME_CONFIG_BASICAITH_USERNAME: pippo
      ME_CONFIG_BASICAITH_PASSWORD: pippo
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
    ports:
      - 8081:8081
    networks: 
      - my_networks

networks:
  my_networks:

volumes:
  mongo_volumes:
  express_volumes:

  