version: '3.8'
services:
  mysql:
      image: mysql:5.7
      restart: always
      environment:
        MYSQL_DATABASE: dbtest  # variabili di configurazione
        MYSQL_USER: pippo # variabili di configurazione
        MYSQL_PASSWORD_FILE: /run/secrets/pg-password # variabili di configurazione
        MYSQL_RANDOM_ROOT_PASSWORD: '1' # variabili di configurazione
      secrets:
        - pg-password #variabile segreta
      volumes:
        - db:/var/lib/mysql
      networks:
        - network2
      deploy:
        replicas: 1
        placement:  
          constraints:
            - node.labels.node == manager   # clausola di deploy sulla label del nodo 
   
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    networks:
      - network2
    deploy:
      replicas: 2
      placement:  
          constraints:
          - node.labels.node == workers #clausola di deploy sulla label del nodo
  
  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: mysql    # variabili di configurazione
      WORDPRESS_DB_USER: pippo    # variabili di configurazione
      WORDPRESS_DB_PASSWORD_FILE: /run/secrets/pg-password    # variabili di configurazione
      WORDPRESS_DB_NAME: dbtest   # variabili di configurazione
    secrets:
      - pg-password #variabile segreta
    volumes:
      - wordpress:/var/www/html
    networks:
      - network2
    deploy:
      replicas: 2
      placement:  
          constraints:
            - node.labels.node == workers #clausola di deploy sulla label del nodo

networks: 
  network2:
volumes:
  wordpress:
  db:
secrets:
  pg-password:            # necessario per poter importare dei secrets 
    external: true      # necessario per poter importare dei secrets 

